services:
  humble_orin:
    container_name: humble_orin
    privileged: true
    network_mode: host
    restart: unless-stopped
    volumes:
      - type: bind
        source: .
        target: /home/ros/ws
    command: ["tail", "-f", "/dev/null"]
    environment:
      - ROS_DOMAIN_ID=0
      - ROS_AUTOMATIC_DISCOVERY_RANGE=SUBNET
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - FASTRTPS_DEFAULT_PROFILES_FILE=/home/ros/ws/no_shm.xml
    build:
      context: .
      args:
        USERNAME: ros
      platforms:
        - "linux/arm64"
    image: humble_orin:latest
