# Configuration
COMMAND := echo \"Hello, world!\"#  CHANGE ME for command to run on container init, escape any double quotes
REMOTE_HOSTNAME := 127.0.0.1#  CHANGE ME to enable remote commands
DOCKER_USER := ros
REMOTE_USER := robot
DOCKER_DIR := /home/${DOCKER_USER}/ws
REMOTE_DIR := /home/${REMOTE_USER}/local_ws
ROS_DISTRO := humble
SERVICE_NAME := humble_orin
CONTAINER_NAME := ${SERVICE_NAME}

# Terminal colors
PL := \033[35;1m#  purple
GN := \033[32;1m#  green
YL := \033[33;1m#  yellow
CY := \033[36;1m#  cyan
RD := \033[31;1m#  red
NC := \033[0m#     reset

# Ensure Make doesn't look for files
.PHONY: build build-nc run run-nc attach attach-r attach-metal stop stop-r status status-r deploy deploy-nc deploy-rebuild deploy-loc


# Displays colored and timestamped log message
# Args: color code, log text
# FIXME: date is static and not dynamic
define log
	@echo "$(1)[$(shell date +%H:%M:%S)][$(shell echo $@ | tr '[:lower:]' '[:upper:]')] $(2)${NC}"
endef

# Same as above, but allows terminal color to bleed into subsequent STDOUT
# Args: color code, log text
define logb
	@echo "$(1)[$(shell date +%H:%M:%S)][$(shell echo $@ | tr '[:lower:]' '[:upper:]')] $(2)"
endef

# Executes command(s) on the remote target
# Args: command (; delineated if multiple, escape double quotes)
define sshexec
	@ssh -t -o LogLevel=ERROR -o BatchMode=yes -o "UserKnownHostsFile=/dev/null" -o StrictHostKeyChecking=no ${REMOTE_USER}@${REMOTE_HOSTNAME} "$(1)"
endef

# Executes command(s) in a running docker container, waiting for it to finish
# Args: command (&& delineated if multiple, escape double quotes)
define docexec
	@docker exec -it -w ${DOCKER_DIR} ${CONTAINER_NAME} /bin/bash -c "$(1)"
endef

# Same as above, but detaches instead of waiting
# Args: command (&& delineated if multiple, escape double quotes)
define docexecd
	@docker exec -itd -w ${DOCKER_DIR} ${CONTAINER_NAME} /bin/bash -c "$(1)"
endef


# Builds the container locally with docker cache
build:
	$(call log,${PL},"Stopping existing local containers")
	@docker compose stop ${SERVICE_NAME}
	$(call log,${PL},"Building local container")
	@docker compose build ${SERVICE_NAME}
	$(call log,${PL},"Local build complete")

# Same as above, but completely rebuilds without docker cache (takes a long time)
build-nc:
	$(call log,${PL},"Stopping existing local containers")
	@docker compose stop ${SERVICE_NAME}
	$(call log,${PL},"Rebuilding local container cachelessly")
	@docker compose build --no-cache ${SERVICE_NAME}
	$(call log,${PL},"Local build complete$")

# Restarts the docker service / container for you and runs colcon build / command (these will persist by default)
run:
	$(call log,${GN},"Stopping existing local containers")
	@docker compose stop ${SERVICE_NAME}
	$(call log,${GN},"Starting local container \(emulation will be used if platform unsupported\)")
	@docker compose up -d ${SERVICE_NAME}
	$(call log,${GN},"Running colcon build")
	$(call docexec,". /opt/ros/${ROS_DISTRO}/install/setup.bash && colcon build")
	$(call log,${GN},"Starting command: ${COMMAND}")
	$(call docexecd,". /opt/ros/${ROS_DISTRO}/install/setup.bash && ${COMMAND}")
	$(call log,${GN},"Local container online")

# Same as above, but wipes all cache generated by colcon
run-nc:
	$(call log,${GN},"Stopping existing local containers")
	@docker compose stop ${SERVICE_NAME}
	$(call log,${GN},"Removing colcon files")
	@rm -rfv build install log
	$(call log,${GN},"Starting local container (emulation will be used if platform unsupported)")
	@docker compose up -d ${SERVICE_NAME}
	$(call log,${GN},"Running colcon build")
	$(call docexec,". /opt/ros/${ROS_DISTRO}/install/setup.bash && colcon build")
	$(call log,${GN},"Starting command: ${COMMAND}")
	$(call docexecd,". /opt/ros/${ROS_DISTRO}/install/setup.bash && . ./install/local_setup.bash && ${COMMAND}")
	$(call log,${GN},"Local container online")

# Attaches to bash shell currently running project container
attach:
	@echo "${PURPLE}[ATTACH] Attaching to locally running container${NC}"
	@docker exec -it -w ${DOCKER_DIR} ${CONTAINER_NAME} /bin/bash
	@echo "${PURPLE}[ATTACH] Detached from locally running container${NC}"

# Attaches to bash shell in relevant container on remote machine
attach-r:
	@echo "${PURPLE}[ATTACH] Attaching to remote container${NC}"
	@ssh -t -o LogLevel=ERROR -o PasswordAuthentication=no -o "UserKnownHostsFile=/dev/null" -o StrictHostKeyChecking=no ${REMOTE_USER}@${REMOTE_HOSTNAME} "docker exec -it -w ${DOCKER_DIR} ${CONTAINER_NAME} /bin/bash"
	@echo "${PURPLE}[ATTACH] Detached from remote container${NC}"

# Attaches SSH session to the AGX Orin itself (outside of container)
attach-metal:
	@echo "${CYAN}[ATTACH] Attaching to remote AGX orin (outside of container)${NC}"
	@ssh -t -o LogLevel=ERROR -o PasswordAuthentication=no -o "UserKnownHostsFile=/dev/null" -o StrictHostKeyChecking=no ${REMOTE_USER}@${REMOTE_HOSTNAME}
	@echo "${CYAN}[ATTACH] Detached from remote AGX orin${NC}"

# Stops relevant containers on host machine and disables persistence
stop:
	@echo "${RED}[STOP] Stopping local container instances${NC}"
	@docker compose stop ${SERVICE_NAME}
	@echo "${RED}[STOP] Container stopped${NC}"

# Stops relevant container on remote machine and disables persistence
stop-r:
	@echo "${RED}[STOP-R] Stopping remote container instances${NC}"
	@ssh -t -o LogLevel=ERROR -o BatchMode=yes -o "UserKnownHostsFile=/dev/null" -o StrictHostKeyChecking=no ${REMOTE_USER}@${REMOTE_HOSTNAME} "cd ${REMOTE_DIR}; docker compose stop ${CONTAINER_NAME}"
	@echo "${RED}[STOP-R] Remote container stopped${NC}"

# Lists locally running containers relevant to this project, images created, and the docker service status
status:
	@echo "\n${GREEN}[STATUS] <<LOCAL CONTAINERS>>"
	@docker ps | grep -e CONTAINER -e ${CONTAINER_NAME}
	@echo "\n${YELLOW}[STATUS] <<LOCAL IMAGES>>"
	@docker image ls | grep -e REPOSITORY -e ${CONTAINER_NAME}
	@echo "\n${CYAN}[STATUS] <<LOCAL DOCKER SERVICE>>"
	@service docker status | grep -e Active

# Lists remote running containers relevant to this project, images
status-r:
	@echo "\n${GREEN}[STATUS-R] <<REMOTE CONTAINERS>>"
	@ssh -o LogLevel=ERROR -o BatchMode=yes -o "UserKnownHostsFile=/dev/null" -o StrictHostKeyChecking=no ${REMOTE_USER}@${REMOTE_HOSTNAME} "docker ps" | grep -e CONTAINER -e ${CONTAINER_NAME}
	@echo "\n${YELLOW}[STATUS-R] <<REMOTE IMAGES>>"
	@ssh -o LogLevel=ERROR -o BatchMode=yes -o "UserKnownHostsFile=/dev/null" -o StrictHostKeyChecking=no ${REMOTE_USER}@${REMOTE_HOSTNAME} "docker image ls" | grep -e REPOSITORY -e ${CONTAINER_NAME}
	@echo "\n${CYAN}[STATUS-R] <<REMOTE DOCKER SERVICE>>"
	@ssh -o LogLevel=ERROR -o BatchMode=yes -o "UserKnownHostsFile=/dev/null" -o StrictHostKeyChecking=no ${REMOTE_USER}@${REMOTE_HOSTNAME} "service docker status" | grep -e Active

# Stops, rebuilds and restarts persistent container on the remote machine
deploy:
	@echo "${YELLOW}[DEPLOY] Deploying container on remote machine${NC}"
	@echo "${YELLOW}[DEPLOY] Transferring files${NC}"
	@rsync -vrz --exclude Makefile --exclude README.md --exclude .git ./* ${REMOTE_USER}@${REMOTE_HOSTNAME}:/home/robot/local_ws
	@echo "${YELLOW}[DEPLOY] Starting remote container${NC}"
	@ssh -t -o LogLevel=ERROR -o BatchMode=yes -o "UserKnownHostsFile=/dev/null" -o StrictHostKeyChecking=no ${REMOTE_USER}@${REMOTE_HOSTNAME} "cd ${REMOTE_DIR}; docker compose stop ${SERVICE_NAME}; docker compose build ${SERVICE_NAME}; docker compose up -d ${SERVICE_NAME}"
	@echo "${YELLOW}[DEPLOY] Running colcon build${NC}"
	@ssh -t -o LogLevel=ERROR -o BatchMode=yes -o "UserKnownHostsFile=/dev/null" -o StrictHostKeyChecking=no ${REMOTE_USER}@${REMOTE_HOSTNAME} "docker exec -it -w ${DOCKER_DIR} ${CONTAINER_NAME} /bin/bash -c \". /opt/ros/${ROS_DISTRO}/install/setup.bash && colcon build\""
	@echo "${YELLOW}[DEPLOY] Starting command${NC}"
	@ssh -t -o LogLevel=ERROR -o BatchMode=yes -o "UserKnownHostsFile=/dev/null" -o StrictHostKeyChecking=no ${REMOTE_USER}@${REMOTE_HOSTNAME} "docker exec -itd -w ${DOCKER_DIR} ${CONTAINER_NAME} /bin/bash -c \". /opt/ros/${ROS_DISTRO}/install/setup.bash && . ./install/local_setup.bash && ${COMMAND}\""
	@echo "${YELLOW}[DEPLOY] Remote container online${NC}"

# Same as above, but with remote colon cache directories removed
deploy-nc:
	@echo "${YELLOW}[DEPLOY-NC] Deploying container on remote machine without colcon cache${NC}"
	@echo "${YELLOW}[DEPLOY-NC] Removing colcon files${NC}"
	@rm -rfv build install log
	@ssh -t -o LogLevel=ERROR -o BatchMode=yes -o "UserKnownHostsFile=/dev/null" -o StrictHostKeyChecking=no ${REMOTE_USER}@${REMOTE_HOSTNAME} "cd ${REMOTE_DIR}; rm -rfv build install log"
	@echo "${YELLOW}[DEPLOY-NC] Syncing directory${NC}"
	@rsync -vrz --exclude Makefile --exclude README.md --exclude .git ./* ${REMOTE_USER}@${REMOTE_HOSTNAME}:/home/robot/local_ws
	@echo "${YELLOW}[DEPLOY-NC] Starting remote container${NC}"
	@ssh -t -o LogLevel=ERROR -o BatchMode=yes -o "UserKnownHostsFile=/dev/null" -o StrictHostKeyChecking=no ${REMOTE_USER}@${REMOTE_HOSTNAME} "cd ${REMOTE_DIR}; docker compose stop ${SERVICE_NAME}; docker compose build ${SERVICE_NAME}; docker compose up -d ${SERVICE_NAME}"
	@echo "${YELLOW}[DEPLOY-NC] Running colcon build${NC}"
	@ssh -t -o LogLevel=ERROR -o BatchMode=yes -o "UserKnownHostsFile=/dev/null" -o StrictHostKeyChecking=no ${REMOTE_USER}@${REMOTE_HOSTNAME} "docker exec -it -w ${DOCKER_DIR} ${CONTAINER_NAME} /bin/bash -c \". /opt/ros/${ROS_DISTRO}/install/setup.bash && colcon build\""
	@echo "${YELLOW}[DEPLOY-NC] Starting command${NC}"
	@ssh -t -o LogLevel=ERROR -o BatchMode=yes -o "UserKnownHostsFile=/dev/null" -o StrictHostKeyChecking=no ${REMOTE_USER}@${REMOTE_HOSTNAME} "docker exec -itd -w ${DOCKER_DIR} ${CONTAINER_NAME} /bin/bash -c \". /opt/ros/${ROS_DISTRO}/install/setup.bash && . ./install/local_setup.bash && ${COMMAND}\""
	@echo "${YELLOW}[DEPLOY-NC] Remote container online${NC}"

# Same as above, but completely rebuilds without remote docker or colcon cache (takes a long time)
deploy-rebuild:
	@echo "${YELLOW}[DEPLOY-REBUILD] Deploying container on remote machine with full cacheless rebuild${NC}"
	@echo "${YELLOW}[DEPLOY-REBUILD] Removing colcon files${NC}"
	@rm -rfv build install log
	@ssh -t -o LogLevel=ERROR -o BatchMode=yes -o "UserKnownHostsFile=/dev/null" -o StrictHostKeyChecking=no ${REMOTE_USER}@${REMOTE_HOSTNAME} "cd ${REMOTE_DIR}; rm -rfv build install log"
	@echo "${YELLOW}[DEPLOY-REBUILD] Syncing directory${NC}"
	@rsync -vrz --exclude Makefile --exclude README.md --exclude ./.git ./* ${REMOTE_USER}@${REMOTE_HOSTNAME}:/home/robot/local_ws
	@echo "${YELLOW}[DEPLOY-REBUILD] Starting remote container${NC}"
	@ssh -t -o LogLevel=ERROR -o BatchMode=yes -o "UserKnownHostsFile=/dev/null" -o StrictHostKeyChecking=no ${REMOTE_USER}@${REMOTE_HOSTNAME} "cd ${REMOTE_DIR}; docker compose stop ${SERVICE_NAME}; docker compose build --no-cache ${SERVICE_NAME}; docker compose up -d ${SERVICE_NAME}"
	@echo "${YELLOW}[DEPLOY-REBUILD] Running colcon build${NC}"
	@ssh -t -o LogLevel=ERROR -o BatchMode=yes -o "UserKnownHostsFile=/dev/null" -o StrictHostKeyChecking=no ${REMOTE_USER}@${REMOTE_HOSTNAME} "docker exec -it -w ${DOCKER_DIR} ${CONTAINER_NAME} /bin/bash -c \". /opt/ros/${ROS_DISTRO}/install/setup.bash && colcon build\""
	@echo "${YELLOW}[DEPLOY-REBUILD] Starting command${NC}"
	@ssh -t -o LogLevel=ERROR -o BatchMode=yes -o "UserKnownHostsFile=/dev/null" -o StrictHostKeyChecking=no ${REMOTE_USER}@${REMOTE_HOSTNAME} "docker exec -itd -w ${DOCKER_DIR} ${CONTAINER_NAME} /bin/bash -c \". /opt/ros/${ROS_DISTRO}/install/setup.bash && . ./install/local_setup.bash && ${COMMAND}\""
	@echo "${YELLOW}[DEPLOY-REBUILD] Remote container online${NC}"

# (UNIMPLEMENTED) transfers existing docker image from host to remote and runs it (use with build/run to compile on host)
deploy-loc:
	@echo "WIP NOT FINISHED"
