# Configuration
COMMAND := echo YOUR COMMAND HERE# MUST UPDATE if you want a command to run on container init, use escape chars for double quotes e.g. \"
REMOTE_HOSTNAME := 192.168.1.146# MUST UPDATE to enable remote commands
REMOTE_USER := robot
DOCKER_USER := ros
REMOTE_DIR := /home/${REMOTE_USER}/local_ws
DOCKER_DIR := /home/${DOCKER_USER}/ws
ROS_DISTRO := humble
SERVICE_NAME := humble_agx_orin
CONTAINER_NAME := humble_agx_orin

# Terminal colors
PURPLE := \033[35;1m
GREEN := \033[32;1m
YELLOW := \033[33;1m
CYAN := \033[36;1m
RED := \033[31;1m
NC := \033[0m

# Builds the container locally with docker cache and runs colcon build
build:
	@echo "${PURPLE}[BUILD] Stopping existing local containers${NC}"
	@docker compose stop ${SERVICE_NAME}
	@echo "${PURPLE}[BUILD] Starting local container build${NC}"
	@docker compose build ${SERVICE_NAME}
	@echo "${PURPLE}[BUILD] Local build complete${NC}"

# Same as above, but completely rebuilds without docker cache (takes a long time)
build-nc:
	@echo "${PURPLE}[BUILD-NC] Stopping existing local containers${NC}"
	@docker compose stop ${SERVICE_NAME}
	@echo "${PURPLE}[BUILD-NC] Starting cacheless container rebuild${NC}"
	@docker compose build --no-cache ${SERVICE_NAME}
	@echo "${PURPLE}[BUILD-NC] Local build complete${NC}"

# Restarts the docker service / container for you and runs colcon build / command (these will persist by default)
run:
	@echo "${GREEN}[RUN] Stopping existing local containers${NC}"
	@docker compose stop ${SERVICE_NAME}
	@echo "${GREEN}[RUN] Starting local container (emulation will be used if platform unsupported)${NC}"
	@docker compose up -d ${SERVICE_NAME}
	@echo "${GREEN}[RUN] Running colcon build${NC}"
	@docker exec -it -w ${DOCKER_DIR} ${CONTAINER_NAME} /bin/bash -c ". /opt/ros/${ROS_DISTRO}/install/setup.bash && colcon build"
	@echo "${GREEN}[RUN] Starting command${NC}"
	@docker exec -itd -w ${DOCKER_DIR} ${CONTAINER_NAME} /bin/bash -c ". /opt/ros/${ROS_DISTRO}/install/setup.bash && ${COMMAND}"
	@echo "${GREEN}[RUN] Local container online${NC}"

# Same as above, but wipes all cache generated by colcon
run-nc:
	@echo "${GREEN}[RUN-NC] Stopping existing local containers${NC}"
	docker compose stop ${SERVICE_NAME}
	@echo "${GREEN}[RUN-NC] Removing colcon files${NC}"
	rm -rfv build install log
	@echo "${GREEN}[RUN-NC] Starting local container (emulation will be used if platform unsupported)${NC}"
	docker compose up -d ${SERVICE_NAME}
	@echo "${GREEN}[RUN-NC] Running colcon build${NC}"
	docker exec -it -w ${DOCKER_DIR} ${CONTAINER_NAME} /bin/bash -c ". /opt/ros/${ROS_DISTRO}/install/setup.bash && colcon build"
	@echo "${GREEN}[RUN-NC] Starting command${NC}"
	docker exec -itd -w ${DOCKER_DIR} ${CONTAINER_NAME} /bin/bash -c ". /opt/ros/${ROS_DISTRO}/install/setup.bash && . ./install/local_setup.bash && ${COMMAND}"
	@echo "${GREEN}[RUN-NC] Local container online${NC}"

# Attaches to bash shell currently running project container
attach:
	@echo "${PURPLE}[ATTACH] Attaching to locally running container${NC}"
	@docker exec -it -w ${DOCKER_DIR} ${CONTAINER_NAME} /bin/bash
	@echo "${PURPLE}[ATTACH] Detached from locally running container${NC}"

# Attaches to bash shell in relevant container on remote machine
attach-r:
	@echo "${PURPLE}[ATTACH] Attaching to remote container${NC}"
	@ssh -t -o LogLevel=ERROR -o PasswordAuthentication=no -o "UserKnownHostsFile=/dev/null" -o StrictHostKeyChecking=no ${REMOTE_USER}@${REMOTE_HOSTNAME} "docker exec -it -w ${DOCKER_DIR} ${CONTAINER_NAME} /bin/bash"
	@echo "${PURPLE}[ATTACH] Detached from remote container${NC}"

# Attaches SSH session to the AGX Orin itself (outside of container)
attach-orin:
	@echo "${CYAN}[ATTACH] Attaching to remote AGX orin (outside of container)${NC}"
	@ssh -t -o LogLevel=ERROR -o PasswordAuthentication=no -o "UserKnownHostsFile=/dev/null" -o StrictHostKeyChecking=no ${REMOTE_USER}@${REMOTE_HOSTNAME}
	@echo "${CYAN}[ATTACH] Detached from remote AGX orin${NC}"

# Stops relevant containers on host machine and disables persistence
stop:
	@echo "${RED}[STOP] Stopping local container instances${NC}"
	@docker compose stop ${SERVICE_NAME}
	@echo "${RED}[STOP] Container stopped${NC}"

# Stops relevant container on remote machine and disables persistence
stop-r:
	@echo "${RED}[STOP-R] Stopping remote container instances${NC}"
	@ssh -t -o LogLevel=ERROR -o BatchMode=yes -o "UserKnownHostsFile=/dev/null" -o StrictHostKeyChecking=no ${REMOTE_USER}@${REMOTE_HOSTNAME} "cd ${REMOTE_DIR}; docker compose stop ${CONTAINER_NAME}"
	@echo "${RED}[STOP-R] Remote container stopped${NC}"

# Lists locally running containers relevant to this project, images created, and the docker service status
status:
	@echo "\n${GREEN}[STATUS] <<LOCAL CONTAINERS>>"
	@docker ps | grep -e CONTAINER -e ${CONTAINER_NAME}
	@echo "\n${YELLOW}[STATUS] <<LOCAL IMAGES>>"
	@docker image ls | grep -e REPOSITORY -e ${CONTAINER_NAME}
	@echo "\n${CYAN}[STATUS] <<LOCAL DOCKER SERVICE>>"
	@service docker status | grep -e Active

# Lists remote running containers relevant to this project, images
status-r:
	@echo "\n${GREEN}[STATUS-R] <<REMOTE CONTAINERS>>"
	@ssh -o LogLevel=ERROR -o BatchMode=yes -o "UserKnownHostsFile=/dev/null" -o StrictHostKeyChecking=no ${REMOTE_USER}@${REMOTE_HOSTNAME} "docker ps" | grep -e CONTAINER -e ${CONTAINER_NAME}
	@echo "\n${YELLOW}[STATUS-R] <<REMOTE IMAGES>>"
	@ssh -o LogLevel=ERROR -o BatchMode=yes -o "UserKnownHostsFile=/dev/null" -o StrictHostKeyChecking=no ${REMOTE_USER}@${REMOTE_HOSTNAME} "docker image ls" | grep -e REPOSITORY -e ${CONTAINER_NAME}
	@echo "\n${CYAN}[STATUS-R] <<REMOTE DOCKER SERVICE>>"
	@ssh -o LogLevel=ERROR -o BatchMode=yes -o "UserKnownHostsFile=/dev/null" -o StrictHostKeyChecking=no ${REMOTE_USER}@${REMOTE_HOSTNAME} "service docker status" | grep -e Active

# Stops, rebuilds and restarts persistent container on the remote machine
deploy:
	@echo "${YELLOW}[DEPLOY] Deploying container on remote machine${NC}"
	@echo "${YELLOW}[DEPLOY] Transferring files${NC}"
	@rsync -vrz --exclude Makefile --exclude README.md --exclude .git ./* ${REMOTE_USER}@${REMOTE_HOSTNAME}:/home/robot/local_ws
	@echo "${YELLOW}[DEPLOY] Starting remote container${NC}"
	@ssh -t -o LogLevel=ERROR -o BatchMode=yes -o "UserKnownHostsFile=/dev/null" -o StrictHostKeyChecking=no ${REMOTE_USER}@${REMOTE_HOSTNAME} "cd ${REMOTE_DIR}; docker compose stop ${SERVICE_NAME}; docker compose build ${SERVICE_NAME}; docker compose up -d ${SERVICE_NAME}"
	@echo "${YELLOW}[DEPLOY] Running colcon build${NC}"
	@ssh -t -o LogLevel=ERROR -o BatchMode=yes -o "UserKnownHostsFile=/dev/null" -o StrictHostKeyChecking=no ${REMOTE_USER}@${REMOTE_HOSTNAME} "docker exec -it -w ${DOCKER_DIR} ${CONTAINER_NAME} /bin/bash -c \". /opt/ros/${ROS_DISTRO}/install/setup.bash && colcon build\""
	@echo "${YELLOW}[DEPLOY] Starting command${NC}"
	@ssh -t -o LogLevel=ERROR -o BatchMode=yes -o "UserKnownHostsFile=/dev/null" -o StrictHostKeyChecking=no ${REMOTE_USER}@${REMOTE_HOSTNAME} "docker exec -itd -w ${DOCKER_DIR} ${CONTAINER_NAME} /bin/bash -c \". /opt/ros/${ROS_DISTRO}/install/setup.bash && . ./install/local_setup.bash && ${COMMAND}\""
	@echo "${YELLOW}[DEPLOY] Remote container online${NC}"

# Same as above, but with remote colon cache directories removed
deploy-nc:
	@echo "${YELLOW}[DEPLOY-NC] Deploying container on remote machine without colcon cache${NC}"
	@echo "${YELLOW}[DEPLOY-NC] Removing colcon files${NC}"
	@rm -rfv build install log
	@ssh -t -o LogLevel=ERROR -o BatchMode=yes -o "UserKnownHostsFile=/dev/null" -o StrictHostKeyChecking=no ${REMOTE_USER}@${REMOTE_HOSTNAME} "cd ${REMOTE_DIR}; rm -rfv build install log"
	@echo "${YELLOW}[DEPLOY-NC] Syncing directory${NC}"
	@rsync -vrz --exclude Makefile --exclude README.md --exclude .git ./* ${REMOTE_USER}@${REMOTE_HOSTNAME}:/home/robot/local_ws
	@echo "${YELLOW}[DEPLOY-NC] Starting remote container${NC}"
	@ssh -t -o LogLevel=ERROR -o BatchMode=yes -o "UserKnownHostsFile=/dev/null" -o StrictHostKeyChecking=no ${REMOTE_USER}@${REMOTE_HOSTNAME} "cd ${REMOTE_DIR}; docker compose stop ${SERVICE_NAME}; docker compose build ${SERVICE_NAME}; docker compose up -d ${SERVICE_NAME}"
	@echo "${YELLOW}[DEPLOY-NC] Running colcon build${NC}"
	@ssh -t -o LogLevel=ERROR -o BatchMode=yes -o "UserKnownHostsFile=/dev/null" -o StrictHostKeyChecking=no ${REMOTE_USER}@${REMOTE_HOSTNAME} "docker exec -it -w ${DOCKER_DIR} ${CONTAINER_NAME} /bin/bash -c \". /opt/ros/${ROS_DISTRO}/install/setup.bash && colcon build\""
	@echo "${YELLOW}[DEPLOY-NC] Starting command${NC}"
	@ssh -t -o LogLevel=ERROR -o BatchMode=yes -o "UserKnownHostsFile=/dev/null" -o StrictHostKeyChecking=no ${REMOTE_USER}@${REMOTE_HOSTNAME} "docker exec -itd -w ${DOCKER_DIR} ${CONTAINER_NAME} /bin/bash -c \". /opt/ros/${ROS_DISTRO}/install/setup.bash && . ./install/local_setup.bash && ${COMMAND}\""
	@echo "${YELLOW}[DEPLOY-NC] Remote container online${NC}"

# Same as above, but completely rebuilds without remote docker or colcon cache (takes a long time)
deploy-rebuild:
	@echo "${YELLOW}[DEPLOY-REBUILD] Deploying container on remote machine with full cacheless rebuild${NC}"
	@echo "${YELLOW}[DEPLOY-REBUILD] Removing colcon files${NC}"
	@rm -rfv build install log
	@ssh -t -o LogLevel=ERROR -o BatchMode=yes -o "UserKnownHostsFile=/dev/null" -o StrictHostKeyChecking=no ${REMOTE_USER}@${REMOTE_HOSTNAME} "cd ${REMOTE_DIR}; rm -rfv build install log"
	@echo "${YELLOW}[DEPLOY-REBUILD] Syncing directory${NC}"
	@rsync -vrz --exclude Makefile --exclude README.md --exclude ./.git ./* ${REMOTE_USER}@${REMOTE_HOSTNAME}:/home/robot/local_ws
	@echo "${YELLOW}[DEPLOY-REBUILD] Starting remote container${NC}"
	@ssh -t -o LogLevel=ERROR -o BatchMode=yes -o "UserKnownHostsFile=/dev/null" -o StrictHostKeyChecking=no ${REMOTE_USER}@${REMOTE_HOSTNAME} "cd ${REMOTE_DIR}; docker compose stop ${SERVICE_NAME}; docker compose build --no-cache ${SERVICE_NAME}; docker compose up -d ${SERVICE_NAME}"
	@echo "${YELLOW}[DEPLOY-REBUILD] Running colcon build${NC}"
	@ssh -t -o LogLevel=ERROR -o BatchMode=yes -o "UserKnownHostsFile=/dev/null" -o StrictHostKeyChecking=no ${REMOTE_USER}@${REMOTE_HOSTNAME} "docker exec -it -w ${DOCKER_DIR} ${CONTAINER_NAME} /bin/bash -c \". /opt/ros/${ROS_DISTRO}/install/setup.bash && colcon build\""
	@echo "${YELLOW}[DEPLOY-REBUILD] Starting command${NC}"
	@ssh -t -o LogLevel=ERROR -o BatchMode=yes -o "UserKnownHostsFile=/dev/null" -o StrictHostKeyChecking=no ${REMOTE_USER}@${REMOTE_HOSTNAME} "docker exec -itd -w ${DOCKER_DIR} ${CONTAINER_NAME} /bin/bash -c \". /opt/ros/${ROS_DISTRO}/install/setup.bash && . ./install/local_setup.bash && ${COMMAND}\""
	@echo "${YELLOW}[DEPLOY-REBUILD] Remote container online${NC}"
