<?xml version="1.0"?>
<robot name="mecabot" xmlns:xacro="http://www.ros.org/wiki/xacro">
  
  <xacro:property name="chassis_width" value="0.3"/>
  <xacro:property name="chassis_length" value="0.4"/>
  <xacro:property name="chassis_height" value="0.15"/>
  <xacro:property name="wheel_radius" value="0.05"/>
  <xacro:property name="wheel_width" value="0.04"/>

  <!-- Base Link (Chassis) -->
  <link name="base_link">
    <visual>
      <geometry><box size="${chassis_length} ${chassis_width} ${chassis_height}"/></geometry>
      <material name="blue"><color rgba="0.2 0.4 0.8 1"/></material>
    </visual>
    <collision><geometry><box size="${chassis_length} ${chassis_width} ${chassis_height}"/></geometry></collision>
    <inertial><mass value="5.0"/><inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/></inertial>
  </link>

  <!-- Wheel Macro -->
  <xacro:macro name="wheel_and_transmission" params="prefix side x_offset y_offset">
    <link name="${prefix}_${side}_wheel_link">
      <visual>
        <origin xyz="0 0 0" rpy="1.5707 0 0"/>
        <geometry><cylinder radius="${wheel_radius}" length="${wheel_width}"/></geometry>
        <material name="black"><color rgba="0.1 0.1 0.1 1"/></material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="1.5707 0 0"/>
        <geometry><cylinder radius="${wheel_radius}" length="${wheel_width}"/></geometry>
      </collision>
      <inertial><mass value="0.5"/><inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.02"/></inertial>
    </link>
    <joint name="${prefix}_${side}_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_${side}_wheel_link"/>
      <origin xyz="${x_offset} ${y_offset} 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
    <transmission name="${prefix}_${side}_wheel_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${prefix}_${side}_wheel_joint">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      </joint>
      <actuator name="${prefix}_${side}_wheel_motor">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>
  </xacro:macro>

  <xacro:wheel_and_transmission prefix="front" side="left" x_offset="0.1" y_offset="0.17" />
  <xacro:wheel_and_transmission prefix="front" side="right" x_offset="0.1" y_offset="-0.17" />
  <xacro:wheel_and_transmission prefix="rear" side="left" x_offset="-0.1" y_offset="0.17" />
  <xacro:wheel_and_transmission prefix="rear" side="right" x_offset="-0.1" y_offset="-0.17" />

  <!-- Lidar Sensor -->
  <link name="laser_link">
    <visual><geometry><cylinder radius="0.05" length="0.04"/></geometry><material name="red"><color rgba="1 0 0 1"/></material></visual>
    <collision><geometry><cylinder radius="0.05" length="0.04"/></geometry></collision>
    <inertial><mass value="0.1"/><inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/></inertial>
  </link>
  <joint name="laser_joint" type="fixed">
    <parent link="base_link"/>
    <child link="laser_link"/>
    <origin xyz="${chassis_length/2} 0 ${chassis_height/2 + 0.02}" rpy="0 0 0"/>
  </joint>

  <!-- GAZEBO PLUGINS FOR GALACTIC -->
  <gazebo>
    <plugin name="gazebo_ros_diff_drive" filename="libgazebo_ros_diff_drive.so">
      <commandTopic>cmd_vel</commandTopic>
      <odometryTopic>odom</odometryTopic>
      <odometryFrame>odom</odometryFrame>
      <robotBaseFrame>base_link</robotBaseFrame>
      
      <!-- *** FIX 1: SPECIFY ALL FOUR JOINTS *** -->
      <leftJoint>front_left_wheel_joint</leftJoint>
      <leftJoint>rear_left_wheel_joint</leftJoint>
      <rightJoint>front_right_wheel_joint</rightJoint>
      <rightJoint>rear_right_wheel_joint</rightJoint>
      
      <wheelSeparation>${chassis_width + 0.04}</wheelSeparation>
      <wheelDiameter>${2*wheel_radius}</wheelDiameter>
      <updateRate>100</updateRate>
    </plugin>
  </gazebo>
  
  <gazebo reference="laser_link">
    <sensor type="ray" name="ray_sensor">
      <pose>0 0 0 0 0 0</pose>
      <visualize>true</visualize>
      <update_rate>10</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>360</samples>
            <resolution>1</resolution>
            <min_angle>-3.14</min_angle>
            <max_angle>3.14</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.1</min>
          <max>12.0</max>
          <resolution>0.01</resolution>
        </range>
      </ray>
      <!-- *** FIX 2: USE THE CORRECT LIDAR PLUGIN NAME *** -->
      <plugin name="gazebo_ros_laser_controller" filename="libgazebo_ros_laser.so">
        <topicName>laser_scan</topicName>
        <frameName>laser_link</frameName>
      </plugin>
    </sensor>
  </gazebo>
</robot>
